# probar cada file de autogenerated con problema.py pasado por parametro
# y comparar el resultado esperado con el obtenido
#
# python3 test_autogenerated.py
#

import os
import sys
import subprocess

def test_autogenerated():
    path = "tests_cases/autogenerated"
    for file in os.listdir(path):
        if file.endswith(".txt"):

            output = subprocess.run(["python3", "problema.py", f"{path}/{file}"], capture_output=True)

            output = output.stdout.decode().split("\n")[-3]
            print(f"Testing {file} {output}")

if __name__ == "__main__":
    test_autogenerated()